name: 'Build Cabal package'
author: 'Wolfgang Jeltsch'
description: 'GitHub action for building Cabal packages'
runs:
  using: composite
  steps:
    - name: 'Get package information'
      shell: sh
      run: cabal update
    - name: 'Actually build the package'
      shell: sh
      run: |
        ghc_versions=$(sed -ne '
          /^tested-with:/ {
            s/^tested-with:  *GHC == { \(.*\) }$/\1/
            s/, / /g
            p
          }
        ' *.cabal)
        for ghc_version in $ghc_versions
        do
          ghcup run --install --ghc $ghc_version -- cabal build ||
          if [ ! "$failure_ghc_versions" ]
          then
            failure_ghc_versions=$ghc_version
          else
            failure_ghc_versions="$failure_ghc_versions, $ghc_version"
          fi
        done
        if [ "$failure_ghc_versions" ]
        then
          echo 'The following versions of GHC' \
               'could not build the package:' \
               "$failure_ghc_versions" \
               >&2
          exit 1
        fi
